import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Header from "../components/ui/header"
import { ThreeJsProvider } from './context/ThreeJsContext';

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Codehub",
  description: "Generated by create next app",
}

// app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ThreeJsProvider>
          <main className="pt-20"> {/* Adjust height based on Header */}
            {children}
          </main>
        </ThreeJsProvider>
      </body>

    </html>
  )
}